spring:
  application:
    name: base-app
  profiles:
    active: kubernetes
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  servlet:
    context-path: /base
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus